// User

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const UPDATE_VERIFICATION_STATUS_REQUEST = "UPDATE_VERIFICATION_STATUS_REQUEST";
export const UPDATE_VERIFICATION_STATUS_SUCCESS = "UPDATE_VERIFICATION_STATUS_SUCCESS"
export const UPDATE_VERIFICATION_STATUS_FAIL = "UPDATE_VERIFICATION_STATUS_FAIL"

export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS"
export const SEND_MAIL_FAIL = "SEND_MAIL_FAIL"

export const SEND_SMS_REQUEST = "SEND_SMS_REQUEST";
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS"
export const SEND_SMS_FAIL = "SEND_SMS_FAIL"

// Employee
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS"
export const GET_EMPLOYEE_FAIL = "GET_EMPLOYEE_FAIL"

export const GET_EMPLOYEE_DETAIL_REQUEST = "GET_EMPLOYEE_DETAIL_REQUEST";
export const GET_EMPLOYEE_DETAIL_SUCCESS = "GET_EMPLOYEE_DETAIL_SUCCESS"
export const GET_EMPLOYEE_DETAIL_FAIL = "GET_EMPLOYEE_DETAIL_FAIL"

export const LOAD_EMPLOYEE_REQUEST = "LOAD_EMPLOYEE_REQUEST";
export const LOAD_EMPLOYEE_SUCCESS = "LOAD_EMPLOYEE_SUCCESS"
export const LOAD_EMPLOYEE_FAIL = "LOAD_EMPLOYEE_FAIL"

export const RESOURECE_ALLOCATION_REQUEST = "RESOURECE_ALLOCATION_REQUEST";
export const RESOURECE_ALLOCATION_SUCCESS = "RESOURECE_ALLOCATION_SUCCESS"
export const RESOURECE_ALLOCATION_FAIL = "RESOURECE_ALLOCATION_FAIL"

export const FORGOTPASSWORD_REQUEST = "FORGOTPASSWORD_REQUEST";
export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS"
export const FORGOTPASSWORD_FAIL = "FORGOTPASSWORD_FAIL"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const AUTH_ERROR = "AUTH_ERROR"

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_FAIL = "GOOGLE_LOGIN_FAIL"

export const USER_LOADED = "USER_LOADED"
export const USER_LOADING = "USER_LOADING"

// Admin
export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS"
export const GET_ADMIN_FAIL = "GET_ADMIN_FAIL"


export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST";
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"

export const LOAD_ADMIN_REQUEST = "LOAD_ADMIN_REQUEST";
export const LOAD_ADMIN_SUCCESS = "LOAD_ADMIN_SUCCESS"
export const LOAD_ADMIN_FAIL = "LOAD_ADMIN_FAIL"

export const ADMIN_FORGOTPASSWORD_REQUEST = "ADMIN_FORGOTPASSWORD_REQUEST";
export const ADMIN_FORGOTPASSWORD_SUCCESS = "ADMIN_FORGOTPASSWORD_SUCCESS"
export const ADMIN_FORGOTPASSWORD_FAIL = "ADMIN_FORGOTPASSWORD_FAIL"

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

export const ADMIN_LOADED = "ADMIN_LOADED"
export const ADMIN_LOADING = "ADMIN_LOADING"

export const REPORT_GENERATE_REQUEST = "REPORT_GENERATE_REQUEST";
export const REPORT_GENERATE_SUCCESS = "REPORT_GENERATE_SUCCESS"
export const REPORT_GENERATE_FAIL = "REPORT_GENERATE_FAIL"

export const GET_REPORT_REQUEST = "GET_REPORT_REQUEST";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS"
export const GET_REPORT_FAIL = "GET_REPORT_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"

// Certificate 
export const GET_CERTIFICATE_REQUEST = "GET_CERTIFICATE_REQUEST";
export const GET_CERTIFICATE_SUCCESS = "GET_CERTIFICATE_SUCCESS"
export const GET_CERTIFICATE_FAIL = "GET_CERTIFICATE_FAIL"

export const REGISTER_CERTIFICATE_REQUEST = "REGISTER_CERTIFICATE_REQUEST";
export const REGISTER_CERTIFICATE_SUCCESS = "REGISTER_CERTIFICATE_SUCCESS"
export const REGISTER_CERTIFICATE_FAIL = "REGISTER_CERTIFICATE_FAIL"

export const UPDATE_CERTIFICATE_STATUS_REQUEST = "UPDATE_CERTIFICATE_STATUS_REQUEST";
export const UPDATE_CERTIFICATE_STATUS_SUCCESS = "UPDATE_CERTIFICATE_STATUS_SUCCESS"
export const UPDATE_CERTIFICATE_STATUS_FAIL = "UPDATE_CERTIFICATE_STATUS_FAIL"

// Aadhar

export const GENERATE_OTP_REQUEST = "GENERATE_OTP_REQUEST";
export const GENERATE_OTP_SUCCESS = "GENERATE_OTP_SUCCESS"
export const GENERATE_OTP_FAIL = "GENERATE_OTP_FAIL"

export const AADHAR_VERIFICATION_REQUEST = "AADHAR_VERIFICATION_REQUEST";
export const AADHAR_VERIFICATION_SUCCESS = "AADHAR_VERIFICATION_SUCCESS"
export const AADHAR_VERIFICATION_FAIL = "AADHAR_VERIFICATION_FAIL"